"use strict";
const mongoose = require("mongoose");
const timestamp = require("mongoose-timestamp");
//const AutoIncrement = require('mongoose-sequence')(mongoose);
//const mongooseLogs = require('mongoose-activitylogs');

const SummarySchema = new mongoose.Schema(
  {
    vat: { type: Boolean, required: false },
    discount: { type: Number, required: false },
    finalPrice: { type: Number, required: true },
    semiFinalPrice: { type: Number, required: false },
    newPrice: { type: Number, required: false },
    quantity: { type: Number, required: true },
    productId: { type: String, required: true },
    name: { type: String, required: true },
    productCode: { type: String, required: true },
    saleRemark: { type: String, required: false },
    imageUrl: { type: String, required: false },
    index: { type: Number, required: true },
  },
  { _id: false }
);

const SaleSchema = new mongoose.Schema(
  {
    customerId: { type: String },
    saleIndex: { type: Number, required: true },
    summary: { type: Map, of: SummarySchema, required: true },
    currency: { type: String },
    organisationId: { type: String, required: true },
    paymentMethod: { type: String, required: true },
    salesDate: { type: String, required: true },
    totalSellingPrice: { type: String, required: false },
    salesNote: { type: String },
    inVoiceId: { type: String },
    invoiceNo: { type: String },
    dueDate: { type: String, required: false },
    receiptId: { type: String },
    receiptNo: { type: String },
    // autoGeneratedIdNo: { type: Boolean, required: true },
    balance: { type: String },
    amountPaid: { type: String },
    deliveryCharge: { type: String, required: true },
    subTotal: { type: String, required: true },
    amountDue: { type: String },
    customerNote: { type: String },
    bankTransactionReference: { type: String },
    status: { type: String, default: "active" },
    customerDetail: {
      firstName: { type: String, required: false },
      lastName: { type: String, required: false },
      email: { type: String, required: false },
      phoneNo: { type: String, required: false },
      address: { type: String, required: false },
      salutation: { type: String, required: false },
    },
    organisation: {
      name: { type: String, required: true },
      imageUrl: {
        link: { type: String, required: false },
        name: { type: String, required: false },
      },
    },
    organisationId: { type: String, required: true },
    branch: {
      name: { type: String, required: false },
      address: { type: String, required: false },
      email: { type: String, required: false },
      phoneNo: { type: String, required: false },
      branchId: { type: String, required: false },
    },
    bankDetails: {
      bankId: { type: String, required: true },
      bankName: { type: String, required: false },
      address: { type: String, required: false },
      accountName: { type: String, required: false },
      accountNo: { type: String, required: false },
    },
    salesPerson: { type: String, required: true },
    QrCode: { type: String, required: false },
  },

  { timestamps: true }
);
// SaleSchema.plugin(AutoIncrement, {inc_field: 'salesId'});

const SaleModel = mongoose.model("sale", SaleSchema, "sale");

module.exports = SaleModel;
