"use strict";
const mongoose = require("mongoose");
const timestamp = require("mongoose-timestamp");
//const mongooseLogs = require('mongoose-activitylogs');

const SummarySchema = new mongoose.Schema(
  {
    vat: { type: Boolean, required: false },
    discount: { type: Number, required: false },
    finalPrice: { type: Number, required: true },
    semiFinalPrice: { type: Number, required: false },
    newPrice: { type: Number, required: false },
    originalRate: { type: Number, required: true },
    costRate: { type: Number, required: true },
    quantity: { type: Number, required: true },
    productId: { type: String, required: true },
    name: { type: String, required: true },
    productCode: { type: String, required: true },
    salesRemark: { type: String, required: false },
    index: { type: Number, required: true },
  },
  { _id: false }
);
const BankDetailsSchema = new mongoose.Schema(
  {
    bankId: { type: String, required: true },
    bankName: { type: String, required: false },
    address: { type: String, required: false },
    accountName: { type: String, required: false },
    accountNumber: { type: String, required: false },
  },
  { _id: false }
);

const ReceiptSchema = new mongoose.Schema(
  {
    customerId: { type: String },
    // autoGeneratedIdNo: { type: Boolean, required: true },
    summary: { type: Map, of: SummarySchema, required: false },
    status: { type: String, required: true },
    currency: { type: String },
    organisation: {
      name: { type: String, required: true },
      imageUrl: {
        link: { type: String, required: false },
        name: { type: String, required: false },
      },
    },
    organisationId: { type: String, required: true },
    sale_id: { type: String, required: false },
    receiptNo: { type: String, required: true },
    paymentMethod: { type: String, value: "receipt" },
    receiptDate: { type: String, required: true },
    balance: { type: Number, required: false },
    amountPaid: { type: String },
    branch: {
      name: { type: String, required: false },
      address: { type: String, required: false },
      email: { type: String, required: false },
      phoneNo: { type: String, required: false },
      branchId: { type: String, required: false },
    },
    customerNote: { type: String },
    salesNote: { type: String },
    status: { type: String, default: "active" },
    customerDetail: {
      firstName: { type: String, required: false },
      lastName: { type: String, required: false },
      email: { type: String, required: false },
      phoneNo: { type: String, required: false },
      address: { type: String, required: false },
      salutation: { type: String, required: false },
    },
    bankDetails: BankDetailsSchema,
    bankTransactionReference: { type: String },
    logs: [
      {
        date: Date,
        user: String,
        userId: String,
        action: String,
        details: String,
        comment: String,
        difference: [{ _id: false, field: String, old: String, new: String }],
        reason: String,
        customerPortal: { type: Boolean, default: false },
      },
    ],

    salesPerson: {
      name: { type: String, required: true },
      id: { type: String, required: true },
    },

    QrCode: { type: String, required: true },
    totalSellingPrice: { type: String, required: false },
    deliveryCharge: { type: String, required: false },
    subTotal: { type: String, required: true },
    linkedInvoiceList: {
      type: [
        {
          invoiceId: { type: String, required: true },
          invoiceNo: { type: String, required: true },
          appliedAmount: { type: String, required: true },
        },
      ],
      required: false,
    },
    isInvoicePayment: { type: Boolean, default: false },
    overPayment: { type: Number, default: 0 },
  },

  { timestamps: true }
);

const ReceiptModel = mongoose.model("receipt", ReceiptSchema, "receipt");

module.exports = ReceiptModel;
